[package]
name = "arboresce-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
arboresce.workspace = true
uniffi.workspace = true

[features]
cli = ["uniffi/cli"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
required-features = ["cli"]

[[example]]
name = "print-name"
path = "tests/fixtures/print_name.rs"
