#ifndef ARBORESCE_H
#define ARBORESCE_H

/* Generated by cbindgen 0.29.4. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "arboresce/export.h"

#define ARBORESCE_ABI_VERSION 65536

typedef uint32_t arboresce_status;

typedef struct arboresce_string_view {
  const char *data;
  size_t len;
} arboresce_string_view;

#define ARBORESCE_OK 0

#define ARBORESCE_INVALID_ARGUMENT 1

#define ARBORESCE_PANIC 2

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

ARBORESCE_API uint32_t arboresce_v1_abi_version(void);

ARBORESCE_API arboresce_status arboresce_v1_name(struct arboresce_string_view *out_name);

ARBORESCE_API arboresce_status arboresce_v1_print_name(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ARBORESCE_H */
