[package]
name = "arboresce-c"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
name = "arboresce_c"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
arboresce.workspace = true
